// components/ProjectCard.tsx

import React, { useContext } from 'react';
import FolderIcon from './icons/FolderIcon.tsx';
import GithubIcon from './icons/GithubIcon.tsx';
import { LanguageContext } from '../contexts/LanguageContext.tsx';

const ProjectCard = ({ project }) => {
  const context = useContext(LanguageContext);
  const lang = context?.language || 'pt';

  return (
    <div className="group relative border border-[#00ff41]/50 bg-black/30 p-4 transition-all duration-300 hover:border-[#00ff41] hover:shadow-[0_0_20px_rgba(0,255,65,0.5)] h-full flex flex-col">
      <div className="flex justify-between items-start mb-2">
        <FolderIcon className="w-8 h-8 text-[#00f0ff]" />
        <div className="flex items-center gap-3">
            {project.githubUrl && (
                 <a href={project.githubUrl} target="_blank" rel="noopener noreferrer" aria-label="GitHub Repository" className="text-[#ff00c1] hover:text-white transition-colors duration-300">
                    <GithubIcon className="w-5 h-5" />
                </a>
            )}
        </div>
      </div>
       <p className="text-xs text-gray-300 mb-1">-rwxr-xr-x 1 guest guest 4096 {new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit' })}</p>
      <h3 className="text-xl font-bold text-[#00ff41] mb-2">{project.name[lang]}</h3>
      <p className="text-gray-300 text-sm mb-4">{project.description[lang]}</p>
      <div className="flex flex-wrap gap-2 mt-auto pt-4">
        {project.techStack.map((tech, index) => (
          <span key={index} className="text-xs bg-[#00f0ff]/10 text-[#00f0ff] px-2 py-1">
            {tech}
          </span>
        ))}
      </div>
    </div>
  );
};

export default ProjectCard;

// src/components/ProjectCard.vue
<template>
  <div class="bg-gray-800 rounded-lg p-6 flex flex-col justify-between h-full transform hover:-translate-y-2 transition-transform duration-300">
    <div>
      <div class="flex justify-between items-start mb-4">
        <FolderIcon />
        <div class="flex space-x-4">
          <a v-if="project.github" :href="project.github" target="_blank" rel="noopener noreferrer">
            <GithubIcon />
          </a>
          <a v-if="project.link" :href="project.link" target="_blank" rel="noopener noreferrer">
            <LinkIcon />
          </a>
        </div>
      </div>
      <h3 class="text-xl font-bold text-green-400 mb-2">{{ projectName }}</h3>
      <p class="text-gray-400 text-sm">{{ projectDescription }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import FolderIcon from './icons/FolderIcon.vue';
import GithubIcon from './icons/GithubIcon.vue';
import LinkIcon from './icons/LinkIcon.vue';
import { useLanguage } from '../composables/useLanguage';

const props = defineProps({
  project: {
    type: Object,
    required: true,
  },
});

const { language } = useLanguage();

const projectName = computed(() => {
  return language.value === 'pt' ? props.project.name_pt : props.project.name_en;
});

const projectDescription = computed(() => {
  return language.value === 'pt' ? props.project.description_pt : props.project.description_en;
});

</script>
